/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Main class for the School Management System
 * Provides navigation to various functionalities such as Account, Subject, Exam, etc.
 * 
 * @Lindsay M Blood
 */
public class Main extends javax.swing.JFrame {

    // User-related variables
    int id;             // User ID
    String uname;       // Username
    String usertype;    // User type (Admin, Teacher, Student, Guest)

    /**
     * Default constructor to initialize the Main form
     */
    public Main() {
        initComponents();
        setIconImage();
        setTitle("Main Page");
    }

    /**
     * Overloaded constructor to set user information
     *
     * @param id       User ID
     * @param username Username
     * @param utype    User Type
     */
    public Main(int id, String username, String utype) {
        initComponents();
        setIconImage();
        setTitle("Main Page");
        this.id = id;
        this.uname = username;
        this.usertype = utype;
        jLabel1.setText(uname);   // Display the username
        jLabel2.setText(utype);   // Display the user type
    }

    /**
     * Method to set the application's icon
     */
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    /**
     * This method initializes the GUI components of the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // Declare and initialize GUI components
        jPanel3 = new javax.swing.JPanel();
        accountbutton = new javax.swing.JButton();
        subjectbutton = new javax.swing.JButton();
        exambutton = new javax.swing.JButton();
        studentbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        teacherbutton = new javax.swing.JButton();
        markbutton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        classbutton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        // JFrame settings
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Panel for navigation buttons
        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // ACCOUNT Button
        accountbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        accountbutton.setText("ACCOUNT");
        accountbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountbutton.addActionListener(evt -> accountbuttonActionPerformed(evt));
        jPanel3.add(accountbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 46));

        // SUBJECT Button
        subjectbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        subjectbutton.setText("SUBJECT");
        subjectbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectbutton.addActionListener(evt -> subjectbuttonActionPerformed(evt));
        jPanel3.add(subjectbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 46));

        // EXAM Button
        exambutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        exambutton.setText("EXAM");
        exambutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exambutton.addActionListener(evt -> exambuttonActionPerformed(evt));
        jPanel3.add(exambutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 160, 46));

        // STUDENT Button
        studentbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        studentbutton.setText("STUDENT");
        studentbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentbutton.addActionListener(evt -> studentbuttonActionPerformed(evt));
        jPanel3.add(studentbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 160, 46));

        // LOGOUT Button
        logoutbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        logoutbutton.setText("LOGOUT");
        logoutbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutbutton.addActionListener(evt -> logoutbuttonActionPerformed(evt));
        jPanel3.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 160, 46));

        // TEACHER Button
        teacherbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        teacherbutton.setText("TEACHER");
        teacherbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherbutton.addActionListener(evt -> teacherbuttonActionPerformed(evt));
        jPanel3.add(teacherbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 160, 46));

        // MARK Button
        markbutton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        markbutton1.setText("MARK");
        markbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        markbutton1.addActionListener(evt -> markbutton1ActionPerformed(evt));
        jPanel3.add(markbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 160, 46));

        // CLASS Button
        classbutton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        classbutton1.setText("CLASS");
        classbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classbutton1.addActionListener(evt -> classbutton1ActionPerformed(evt));
        jPanel3.add(classbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 160, 46));

        // Add navigation panel to the JFrame
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        // Panel for user details and logo
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // USERNAME Label
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("USERNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 14, 96, -1));

        // USER TYPE Label
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("USER TYPE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 50, 93, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 6, 80, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("USER TYPE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 50, 80, -1));

        // Logo
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 181, 394, -1));

        // Developer credits
        jLabel7.setText("Developed by:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Lindsay Blood");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(evt -> handleDeveloperCredit());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, -1));

        // Add details panel to the JFrame
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 0, 590, 670));

        // Menu bar
        jMenu1.setText("About Project");
        jMenu1.addMouseListener(evt -> handleAboutMenu());
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);
        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }

    // Event handlers for buttons
    private void accountbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        User u = new User(id, uname, usertype);
        u.setVisible(true);
        this.setVisible(false);
    }

    private void subjectbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        Subject s = new Subject(id, uname, usertype);
        s.setVisible(true);
        this.setVisible(false);
    }

    private void exambuttonActionPerformed(java.awt.event.ActionEvent evt) {
        Exam e = new Exam(id, uname, usertype);
        e.setVisible(true);
        this.setVisible(false);
    }

    private void studentbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        Student s = new Student(id, uname, usertype);
        s.setVisible(true);
        this.setVisible(false);
    }

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }

    private void teacherbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        Teacher t = new Teacher(id, uname, usertype);
        t.setVisible(true);
        this.setVisible(false);
    }

    private void markbutton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Mark m = new Mark(id, uname, usertype);
        m.setVisible(true);
        this.setVisible(false);
    }

    private void classbutton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Classes c = new Classes(id, uname, usertype);
        c.setVisible(true);
        this.setVisible(false);
    }

    private void handleDeveloperCredit() {
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/naveenkumar-j"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void handleAboutMenu() {
        About a = new About();
        a.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Main method to start the application
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton accountbutton;
    private javax.swing.JButton classbutton1;
    private javax.swing.JButton exambutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton markbutton1;
    private javax.swing.JButton studentbutton;
    private javax.swing.JButton subjectbutton;
    private javax.swing.JButton teacherbutton;
}
